## Imports

In [13]:
import numpy as np
import pandas as pd
import life_quality_and_government.utils.paths as path

# Load Data

In [14]:
wdi_dir = path.data_raw_dir('WDI_csv/WDIData.csv')
wdi=pd.read_csv(wdi_dir)  #world development indicators

# View and prepare

## WDI

In [20]:
wdi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.511262,16.966046,17.411737,17.808234,18.179760,18.558937,18.949636,19.333168,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,32.224027,32.046478,31.323579,33.312163,38.380433,39.754201,42.168241,43.640661,NaN,NaN
2,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,20.525353,19.461383,17.790698,16.553470,23.907897,24.624725,26.813900,28.841150,NaN,NaN
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,66.303599,66.496010,65.828988,66.926692,68.722184,71.085418,71.994933,73.589886,NaN,NaN
4,Africa Eastern and Southern,AFE,Account ownership at a financial institution o...,FX.OWN.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### WDI 2019

In [16]:
# Creating pivot table that will contain the WDI features as columns,
# the countries as rows and the 2019 values in the cells.

wdi_2019 = (wdi
            .pivot_table(values='2019',index='Country Name', columns="Indicator Name")
            .reset_index()
            )
wdi_2019

Indicator Name,Country Name,ARI treatment (% of children under 5 taken to a health provider),Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Adequacy of social insurance programs (% of total welfare of beneficiary households),Adequacy of social protection and labor programs (% of total welfare of beneficiary households),Adequacy of social safety net programs (% of total welfare of beneficiary households),Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households),...,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),Young people (ages 15-24) newly infected with HIV
0,Afghanistan,NaN,36.000000,97.700000,96.902190,100.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.900000,500.0
1,Africa Eastern and Southern,NaN,19.333168,43.640661,28.841150,73.589886,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.062444,NaN
2,Africa Western and Central,NaN,13.843047,51.341421,26.589368,82.708881,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.990050,NaN
3,Albania,NaN,80.699997,100.000000,100.000000,100.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.300000,100.0
4,Algeria,NaN,99.300003,99.500000,98.681056,99.800000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,3.800000,45.500000,200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,West Bank and Gaza,NaN,NaN,100.000000,100.000000,100.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,World,NaN,66.178227,90.097011,82.554040,97.276535,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.600000,430000.0
262,"Yemen, Rep.",NaN,60.900002,72.751701,60.632894,93.146530,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.300000,200.0
263,Zambia,NaN,15.700000,43.000000,13.939443,79.878265,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.500000,27000.0
264,Zimbabwe,48.0,30.000000,41.089108,20.051849,85.364670,15.862261,22.702797,26.524783,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.418352,33.658057,60.200000,9600.0

In [17]:
df1 = pd.DataFrame()

# I will only use the GDPs from the WDI.
df1['Country Name'] = wdi_2019['Country Name']
df1['GDP_pc'] = wdi_2019['GDP per capita (current US$)']
df1['GDP_pc_PPP'] = wdi_2019['GDP per capita, PPP (current international $)']
df1['GDP_growth'] = wdi_2019['GDP per capita growth (annual %)']
df1

                    Country Name        GDP_pc    GDP_pc_PPP  GDP_growth
0                    Afghanistan    494.179350   2152.366489    1.535637
1    Africa Eastern and Southern   1530.059177   3842.578511   -0.544414
2     Africa Western and Central   1777.918672   4335.199547    0.492953
3                        Albania   5395.659532  14012.976435    2.549359
4                        Algeria   3989.668276  12009.248208   -0.934556
..                           ...           ...           ...         ...
260           West Bank and Gaza   3656.858271   6509.568335   -1.151614
261                        World  11397.086000  17548.147215    1.520328
262                  Yemen, Rep.           NaN           NaN         NaN
263                       Zambia   1305.001031   3617.200014   -1.451364
264                     Zimbabwe   1316.740657   3783.547898   -7.468627

[265 rows x 4 columns]

In [18]:
df1.to_csv(path.data_interim_dir('wdi_2019.csv'), index=False)

## Argentina time series

In [30]:
wdi_arg = (wdi
    .groupby(['Country Name','Indicator Name']).mean().T['Argentina']
    .drop('Unnamed: 65', axis=0)
    .loc['1995':'2020',:]
            )[['GDP per capita (current US$)']]
wdi_arg.to_csv(path.data_processed_dir('wdi_hist_arg.csv'), index=False)